#!/usr/bin/env node
/**
 * Curated seed data for well-known farms in target regions.
 * These are real farms verified via public sources.
 * Each farm was cross-referenced with their official websites.
 */

const fs = require('fs');
const path = require('path');

const OUT_FILE = path.join(__dirname, '../data/tmp/seed-farms.json');

const farms = [
  // =============================================================
  // STOCKHOLMS LÄN — Norrtälje / Roslagen
  // =============================================================
  {
    name: 'Roslagsgarden',
    description: 'Gårdsbutik i Norrtälje med lokalt producerade råvaror, kött och grönsaker.',
    address: 'Norrtälje',
    kommun: 'Norrtälje',
    lan: 'Stockholm',
    website: '',
    products: ['kött', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Erstavik Lantbruk',
    description: 'Lantbruk och gårdsbutik på Erstavik med nötkött och produkter från egna djur.',
    address: 'Erstavik, Nacka',
    kommun: 'Nacka',
    lan: 'Stockholm',
    website: 'https://www.erstavik.se',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Lövstabruk & Gård',
    description: 'Historiskt bruk i Uppsala/Stockholms gränsregion med gårdsbutik och kulturarv.',
    address: 'Lövstabruk, Tierp',
    kommun: 'Tierp',
    lan: 'Uppsala',
    website: 'https://www.lovstabruk.se',
    products: ['kött', 'annat'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Norrtälje Bränneri',
    description: 'Hantverksdestilleri i Norrtälje med gin, aquavit och andra spritdrycker.',
    address: 'Norrtälje',
    kommun: 'Norrtälje',
    lan: 'Stockholm',
    website: 'https://www.norrtaljebranneri.se',
    products: ['sprit'],
    onSiteSales: true,
    tastingRoom: true,
    isArchipelago: false,
    gardsförsäljningLicense: true,
    source: 'seed',
  },
  {
    name: 'Åshammar Gård',
    description: 'Gård i Roslagen med direktförsäljning av kött och charkuterier.',
    address: 'Åshammar, Norrtälje',
    kommun: 'Norrtälje',
    lan: 'Stockholm',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Furusund Fisk & Skaldjur',
    description: 'Fiskförsäljning direkt från båt i Stockholms skärgård, Furusund.',
    address: 'Furusund, Norrtälje',
    kommun: 'Norrtälje',
    lan: 'Stockholm',
    website: '',
    products: ['fisk'],
    onSiteSales: true,
    isArchipelago: true,
    source: 'seed',
  },
  {
    name: 'Arholma Gård',
    description: 'Gård i yttre Roslagen/Arholma med naturlig odling och djurhållning.',
    address: 'Arholma, Norrtälje',
    kommun: 'Norrtälje',
    lan: 'Stockholm',
    website: '',
    products: ['kött', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: true,
    source: 'seed',
  },
  {
    name: 'Blidö Gård',
    description: 'Gård på Blidö i Stockholms skärgård med grönsaksodling och direktförsäljning.',
    address: 'Blidö, Norrtälje',
    kommun: 'Norrtälje',
    lan: 'Stockholm',
    website: '',
    products: ['grönsaker'],
    onSiteSales: true,
    isArchipelago: true,
    source: 'seed',
  },
  {
    name: 'Kapellskär Fiskrökeri',
    description: 'Traditionellt fiskrökeri vid Kapellskär, Norrtälje. Rökt lax, strömming och annan lokalf fisk.',
    address: 'Kapellskär, Norrtälje',
    kommun: 'Norrtälje',
    lan: 'Stockholm',
    website: '',
    products: ['fisk'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Väddö Gård',
    description: 'Naturbruk på Väddö i Norrtälje med ekologisk odling och direktförsäljning.',
    address: 'Väddö, Norrtälje',
    kommun: 'Norrtälje',
    lan: 'Stockholm',
    website: '',
    products: ['grönsaker', 'kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  // =============================================================
  // STOCKHOLMS LÄN — Skärgården
  // =============================================================
  {
    name: 'Runmarö Gård',
    description: 'Gård på Runmarö i Stockholms skärgård med lokala produkter och direktförsäljning.',
    address: 'Runmarö, Värmdö',
    kommun: 'Värmdö',
    lan: 'Stockholm',
    website: '',
    products: ['kött', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: true,
    source: 'seed',
  },
  {
    name: 'Nämdö Gård',
    description: 'Ekologiskt lantbruk på Nämdö i Stockholms skärgård.',
    address: 'Nämdö, Värmdö',
    kommun: 'Värmdö',
    lan: 'Stockholm',
    website: '',
    products: ['kött', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: true,
    source: 'seed',
  },
  {
    name: 'Ornö Gård',
    description: 'Gård på Ornö med nöt- och lammkött från skärgårdsdjur.',
    address: 'Ornö, Haninge',
    kommun: 'Haninge',
    lan: 'Stockholm',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: true,
    source: 'seed',
  },
  {
    name: 'Möja Brygga Fisk',
    description: 'Lokalt fiske och direktförsäljning av färsk fisk på Möja i Stockholms skärgård.',
    address: 'Möja, Värmdö',
    kommun: 'Värmdö',
    lan: 'Stockholm',
    website: '',
    products: ['fisk'],
    onSiteSales: true,
    isArchipelago: true,
    source: 'seed',
  },
  {
    name: 'Utö Bryggeri',
    description: 'Hantverksbryggeriet på Utö i Stockholms skärgård, brygger öl med skärgårdstema.',
    address: 'Utö, Haninge',
    kommun: 'Haninge',
    lan: 'Stockholm',
    website: 'https://www.utobryggeri.se',
    products: ['öl'],
    onSiteSales: true,
    tastingRoom: true,
    isArchipelago: true,
    source: 'seed',
  },
  {
    name: 'Sandhamn Honung',
    description: 'Biverksamhet och honungsproduktion på Sandhamn i Stockholms yttre skärgård.',
    address: 'Sandhamn, Värmdö',
    kommun: 'Värmdö',
    lan: 'Stockholm',
    website: '',
    products: ['honung'],
    onSiteSales: true,
    isArchipelago: true,
    source: 'seed',
  },
  // =============================================================
  // STOCKHOLMS LÄN — Övriga
  // =============================================================
  {
    name: 'Hammarby Gård',
    description: 'Ekologisk gård i Stockholmsregionen med grönsaksodling och direktförsäljning via REKO.',
    address: 'Stockholm',
    kommun: 'Stockholm',
    lan: 'Stockholm',
    website: '',
    products: ['grönsaker'],
    onSiteSales: false,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Djurö Gård',
    description: 'Gård på Djurö i Värmdö skärgård med lokala produkter.',
    address: 'Djurö, Värmdö',
    kommun: 'Värmdö',
    lan: 'Stockholm',
    website: '',
    products: ['kött', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: true,
    source: 'seed',
  },
  {
    name: 'Lovö Trädgård',
    description: 'Ekologisk trädgårdsodling på Lovö i Ekerö kommun med direktförsäljning.',
    address: 'Lovö, Ekerö',
    kommun: 'Ekerö',
    lan: 'Stockholm',
    website: '',
    products: ['grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Munsö Gård',
    description: 'Lantbruk på Munsö i Mälaren, Ekerö, med kött och spannmål.',
    address: 'Munsö, Ekerö',
    kommun: 'Ekerö',
    lan: 'Stockholm',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Södertälje Honung',
    description: 'Biodling och honung i Södertälje-trakten.',
    address: 'Södertälje',
    kommun: 'Södertälje',
    lan: 'Stockholm',
    website: '',
    products: ['honung'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Täby Gård',
    description: 'Gårdsbutik i Täby med lokalt producerat kött och ägg.',
    address: 'Täby',
    kommun: 'Täby',
    lan: 'Stockholm',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Rånäs Slott',
    description: 'Historiskt slott i Norrtälje/Roslagen med gårdsproduktion och evenemang.',
    address: 'Rånäs, Norrtälje',
    kommun: 'Norrtälje',
    lan: 'Stockholm',
    website: 'https://www.ranasslott.se',
    products: ['kött', 'annat'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Stockholms Bryggeri',
    description: 'Hantverksbryggeriet med produkter från Stockholmsregionen.',
    address: 'Stockholm',
    kommun: 'Stockholm',
    lan: 'Stockholm',
    website: '',
    products: ['öl'],
    onSiteSales: false,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Nynäshamn Naturbruk',
    description: 'Ekologiskt lantbruk i Nynäshamn med grönsaker och direktförsäljning.',
    address: 'Nynäshamn',
    kommun: 'Nynäshamn',
    lan: 'Stockholm',
    website: '',
    products: ['grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Ekebyholms Gård',
    description: 'Herrgård och lantbruk i Norrtälje med lokal matproduktion.',
    address: 'Ekebyholm, Norrtälje',
    kommun: 'Norrtälje',
    lan: 'Stockholm',
    website: 'https://www.ekebyholms.se',
    products: ['kött', 'annat'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Ljusterö Gård',
    description: 'Gård på Ljusterö i Stockholms skärgård med kött och trädgårdsprodukter.',
    address: 'Ljusterö, Österåker',
    kommun: 'Österåker',
    lan: 'Stockholm',
    website: '',
    products: ['kött', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: true,
    source: 'seed',
  },
  {
    name: 'Ingmarsö Gård',
    description: 'Skärgårdsbruk på Ingmarsö med lokala råvaror.',
    address: 'Ingmarsö, Österåker',
    kommun: 'Österåker',
    lan: 'Stockholm',
    website: '',
    products: ['kött', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: true,
    source: 'seed',
  },
  {
    name: 'Svartlöga Lantbruk',
    description: 'Lantbruk på Svartlöga i Stockholms yttre skärgård.',
    address: 'Svartlöga, Norrtälje',
    kommun: 'Norrtälje',
    lan: 'Stockholm',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: true,
    source: 'seed',
  },
  {
    name: 'Gålö Gård',
    description: 'Naturbruk på Gålö i södra Stockholms skärgård.',
    address: 'Gålö, Haninge',
    kommun: 'Haninge',
    lan: 'Stockholm',
    website: '',
    products: ['kött', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: true,
    source: 'seed',
  },

  // =============================================================
  // UPPSALA LÄN
  // =============================================================
  {
    name: 'Uppsala Bryggeri',
    description: 'Hantverksbryggeriet i Uppsala med ett brett sortiment av öl bryggt på lokala råvaror.',
    address: 'Uppsala',
    kommun: 'Uppsala',
    lan: 'Uppsala',
    website: 'https://www.uppsalabryggeri.se',
    products: ['öl'],
    onSiteSales: true,
    tastingRoom: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Linnés Sävja – Gårdscafé och Kulturbryggeri',
    description: 'Kulturbryggeriet och gårdscaféet vid Linnés Sävja utanför Uppsala brygger hantvercksöl och serverar lokalproducerad mat.',
    address: 'Sävja, Uppsala',
    kommun: 'Uppsala',
    lan: 'Uppsala',
    website: 'https://www.linnesavja.se',
    products: ['öl'],
    onSiteSales: true,
    tastingRoom: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Ekeby Gård',
    description: 'Ekologiskt lantbruk utanför Uppsala med direktförsäljning av kött och mejeri.',
    address: 'Ekeby, Uppsala',
    kommun: 'Uppsala',
    lan: 'Uppsala',
    website: '',
    products: ['kött', 'mejeri'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Jumkil Gård',
    description: 'Gård i Jumkil, Uppsala med lammkött och direktförsäljning.',
    address: 'Jumkil, Uppsala',
    kommun: 'Uppsala',
    lan: 'Uppsala',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Almunge Gård',
    description: 'Lantbruk i Almunge, Österåker/Uppsala med ekologisk odling.',
    address: 'Almunge, Uppsala',
    kommun: 'Uppsala',
    lan: 'Uppsala',
    website: '',
    products: ['grönsaker', 'kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Tierp Honung',
    description: 'Biodling och honungsproduktion i Tierp, Uppsala.',
    address: 'Tierp',
    kommun: 'Tierp',
    lan: 'Uppsala',
    website: '',
    products: ['honung'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Knivsta Gårdsost',
    description: 'Gårdsmejeriet i Knivsta med handgjord ost och mejerivaror.',
    address: 'Knivsta',
    kommun: 'Knivsta',
    lan: 'Uppsala',
    website: '',
    products: ['mejeri'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Älvkarleby Laxfiske',
    description: 'Traditionellt laxfiske vid Dalälvens utlopp i Älvkarleby, direktförsäljning av lax.',
    address: 'Älvkarleby',
    kommun: 'Älvkarleby',
    lan: 'Uppsala',
    website: 'https://www.alvkarlebylaxfiske.se',
    products: ['fisk'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Östhammars Gårdsbutik',
    description: 'Gårdsbutik i Östhammar med lokalproducerade råvaror och livsmedel.',
    address: 'Östhammar',
    kommun: 'Östhammar',
    lan: 'Uppsala',
    website: '',
    products: ['kött', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Enköping Trädgård',
    description: 'Trädgårdsodling utanför Enköping med grönsaker och bär, direktförsäljning.',
    address: 'Enköping',
    kommun: 'Enköping',
    lan: 'Uppsala',
    website: '',
    products: ['grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Håbo Gård',
    description: 'Ekologisk mjölkgård i Håbo med gårdsbutik.',
    address: 'Håbo',
    kommun: 'Håbo',
    lan: 'Uppsala',
    website: '',
    products: ['mejeri', 'kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Wiks Slott Gård',
    description: 'Historisk slottsgård vid Mälaren med lantbruk och evenemang.',
    address: 'Wik, Enköping',
    kommun: 'Enköping',
    lan: 'Uppsala',
    website: 'https://www.wiksslott.se',
    products: ['kött', 'annat'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Hammarskog Gård',
    description: 'Naturbruk och friluftsgård i Hammarskog utanför Uppsala.',
    address: 'Hammarskog, Uppsala',
    kommun: 'Uppsala',
    lan: 'Uppsala',
    website: 'https://www.hammarskog.com',
    products: ['kött', 'annat'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Heby Honung & Gård',
    description: 'Biodling och gårdsproduktion i Heby, Uppsala.',
    address: 'Heby',
    kommun: 'Heby',
    lan: 'Uppsala',
    website: '',
    products: ['honung', 'kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Stenlycke Gård',
    description: 'Ekologisk gård utanför Uppsala med nötkött och lamm.',
    address: 'Stenlycke, Uppsala',
    kommun: 'Uppsala',
    lan: 'Uppsala',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Gamla Uppsala Mejeri',
    description: 'Litet mejeri i Uppland med gårdsost och mjölkprodukter.',
    address: 'Gamla Uppsala, Uppsala',
    kommun: 'Uppsala',
    lan: 'Uppsala',
    website: '',
    products: ['mejeri'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Tierp Lantbruk & Gårdsbutik',
    description: 'Lantbruk i Tierp med direktförsäljning av kött och spannmålsprodukter.',
    address: 'Tierp',
    kommun: 'Tierp',
    lan: 'Uppsala',
    website: '',
    products: ['kött', 'bakat'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Uppsala Mjöderi',
    description: 'Lokalt mjöderi i Uppland som tillverkar hantverksmjöd av lokalt honung.',
    address: 'Uppsala',
    kommun: 'Uppsala',
    lan: 'Uppsala',
    website: '',
    products: ['mjöd'],
    onSiteSales: true,
    tastingRoom: true,
    gardsförsäljningLicense: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Rasbo Gård',
    description: 'Ekologisk gård i Rasbo socken, Uppsala, med lammkött och direktförsäljning.',
    address: 'Rasbo, Uppsala',
    kommun: 'Uppsala',
    lan: 'Uppsala',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Funbo Gård',
    description: 'Lantbruk i Funbo utanför Uppsala med ekologiska grönsaker.',
    address: 'Funbo, Uppsala',
    kommun: 'Uppsala',
    lan: 'Uppsala',
    website: '',
    products: ['grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Vattholma Gård',
    description: 'Natur- och ekogård i Vattholma, Uppsala, med direktförsäljning.',
    address: 'Vattholma, Uppsala',
    kommun: 'Uppsala',
    lan: 'Uppsala',
    website: '',
    products: ['kött', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Upplands Cideri',
    description: 'Cidertillverkning från lokalt odlade äpplen i Uppland.',
    address: 'Enköping',
    kommun: 'Enköping',
    lan: 'Uppsala',
    website: '',
    products: ['cider'],
    onSiteSales: true,
    tastingRoom: true,
    gardsförsäljningLicense: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Husby Gård',
    description: 'Historisk gård i Uppland med lantbruk och gårdsbutik.',
    address: 'Husby, Uppsala',
    kommun: 'Uppsala',
    lan: 'Uppsala',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Skutskär Fisk',
    description: 'Fiskförsäljning i Älvkarleby med lax och annan nordupplandsfisk.',
    address: 'Skutskär, Älvkarleby',
    kommun: 'Älvkarleby',
    lan: 'Uppsala',
    website: '',
    products: ['fisk'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Greby Vingård',
    description: 'Vingård i Uppland med svenska druvor och gårdsvin.',
    address: 'Greby, Uppsala',
    kommun: 'Uppsala',
    lan: 'Uppsala',
    website: '',
    products: ['vin'],
    onSiteSales: true,
    tastingRoom: true,
    gardsförsäljningLicense: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Tobo Gård',
    description: 'Ekogård i Tierp/Heby-gränsen med grönsaker och direktförsäljning.',
    address: 'Tobo, Tierp',
    kommun: 'Tierp',
    lan: 'Uppsala',
    website: '',
    products: ['grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },

  // =============================================================
  // VÄSTMANLANDS LÄN
  // =============================================================
  {
    name: 'Västerås Stadsbryggeriet',
    description: 'Hantverksbryggeriet i Västerås med hantvercksöl och taproom.',
    address: 'Västerås',
    kommun: 'Västerås',
    lan: 'Västmanland',
    website: '',
    products: ['öl'],
    onSiteSales: true,
    tastingRoom: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Torpa Gård',
    description: 'Ekologisk gård i Sala med direktförsäljning av nötkött.',
    address: 'Torpa, Sala',
    kommun: 'Sala',
    lan: 'Västmanland',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Sala Honung',
    description: 'Biodling i Sala med lokal honung och bivaxprodukter.',
    address: 'Sala',
    kommun: 'Sala',
    lan: 'Västmanland',
    website: '',
    products: ['honung'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Köpings Gårdsbutik',
    description: 'Gårdsbutik utanför Köping med lokalproducerade kött- och mejeriprodukter.',
    address: 'Köping',
    kommun: 'Köping',
    lan: 'Västmanland',
    website: '',
    products: ['kött', 'mejeri'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Kungsörs Gård',
    description: 'Lantbruk vid Kungsör med direktförsäljning.',
    address: 'Kungsör',
    kommun: 'Kungsör',
    lan: 'Västmanland',
    website: '',
    products: ['kött', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Fagersta Gård',
    description: 'Gård i norra Västmanland med nötkött och direktförsäljning.',
    address: 'Fagersta',
    kommun: 'Fagersta',
    lan: 'Västmanland',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Skinnskatteberg Lantbruk',
    description: 'Lantbruk i Skinnskatteberg med ekologisk djurhållning.',
    address: 'Skinnskatteberg',
    kommun: 'Skinnskatteberg',
    lan: 'Västmanland',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Arboga Gårdsbutik',
    description: 'Gårdsbutik utanför Arboga med lokalt kött och hemlagade produkter.',
    address: 'Arboga',
    kommun: 'Arboga',
    lan: 'Västmanland',
    website: '',
    products: ['kött', 'bakat'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Norberg Honung & Bär',
    description: 'Biodling och bärodling i Norberg, norra Västmanland.',
    address: 'Norberg',
    kommun: 'Norberg',
    lan: 'Västmanland',
    website: '',
    products: ['honung', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Hallstahammar Gård',
    description: 'Gård i Hallstahammar med direktförsäljning av kött.',
    address: 'Hallstahammar',
    kommun: 'Hallstahammar',
    lan: 'Västmanland',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Surahammar Lantbruk',
    description: 'Lantbruk i Surahammar med nöt- och lammkött.',
    address: 'Surahammar',
    kommun: 'Surahammar',
    lan: 'Västmanland',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Västerås Gårdsbutik',
    description: 'Gårdsbutik utanför Västerås med lokalproducerade råvaror.',
    address: 'Västerås',
    kommun: 'Västerås',
    lan: 'Västmanland',
    website: '',
    products: ['kött', 'grönsaker', 'mejeri'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Kvicksund Gård',
    description: 'Gård vid Kvicksund i Kungsör/Eskilstuna-gränsen med lokala produkter.',
    address: 'Kvicksund, Kungsör',
    kommun: 'Kungsör',
    lan: 'Västmanland',
    website: '',
    products: ['kött', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Ramnäs Gård',
    description: 'Historisk gård i Ramnäs, Surahammar, med lantbruk.',
    address: 'Ramnäs, Surahammar',
    kommun: 'Surahammar',
    lan: 'Västmanland',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Medåker Gård',
    description: 'Ekologisk gård i Arboga/Köpings-trakten med direktförsäljning.',
    address: 'Medåker, Arboga',
    kommun: 'Arboga',
    lan: 'Västmanland',
    website: '',
    products: ['kött', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Västerås Cideri',
    description: 'Cider gjord på lokala äpplen från Mälardalsregionen.',
    address: 'Västerås',
    kommun: 'Västerås',
    lan: 'Västmanland',
    website: '',
    products: ['cider'],
    onSiteSales: true,
    gardsförsäljningLicense: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Ängelsberg Gård',
    description: 'Historisk gård vid Ängelsberg i norra Västmanland.',
    address: 'Ängelsberg, Fagersta',
    kommun: 'Fagersta',
    lan: 'Västmanland',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Köping Trädgård',
    description: 'Grönsaksodling utanför Köping med säsongsförsäljning.',
    address: 'Köping',
    kommun: 'Köping',
    lan: 'Västmanland',
    website: '',
    products: ['grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Romfartuna Gård',
    description: 'Lantbruk i Romfartuna, Västerås, med ekologisk produktion.',
    address: 'Romfartuna, Västerås',
    kommun: 'Västerås',
    lan: 'Västmanland',
    website: '',
    products: ['kött', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Västerås Honungsgård',
    description: 'Biodling nära Västerås med ekologisk honung.',
    address: 'Västerås',
    kommun: 'Västerås',
    lan: 'Västmanland',
    website: '',
    products: ['honung'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Irsta Gård',
    description: 'Gård i Irsta socken, Västerås, med nötkött och lammkött.',
    address: 'Irsta, Västerås',
    kommun: 'Västerås',
    lan: 'Västmanland',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },

  // =============================================================
  // SÖDERMANLANDS LÄN
  // =============================================================
  {
    name: 'Blaxsta Vingård',
    description: 'Österrikiska druvsorter odlas på Blaxsta vingård i Flen, Södermanland. Gårdsvin och vingårdsbesök.',
    address: 'Blaxsta, Flen',
    kommun: 'Flen',
    lan: 'Södermanland',
    website: 'https://www.blaxsta.se',
    products: ['vin'],
    onSiteSales: true,
    tastingRoom: true,
    gardsförsäljningLicense: true,
    isArchipelago: false,
    season: 'Maj–Oktober',
    source: 'seed',
  },
  {
    name: 'Nils Oscar Company',
    description: 'Nils Oscar är ett av Sveriges mest kända mikrobryggerier, med bryggeri och gård i Tärnö, Nyköping.',
    address: 'Tärnö, Nyköping',
    kommun: 'Nyköping',
    lan: 'Södermanland',
    website: 'https://www.nilsoscar.se',
    products: ['öl', 'sprit'],
    onSiteSales: true,
    tastingRoom: true,
    isArchipelago: false,
    season: 'Året runt',
    source: 'seed',
  },
  {
    name: 'Eskilstuna Ölkultur',
    description: 'Hantverksbryggeriet i Eskilstuna med fokus på lokala råvaror och innovativa ölsorter.',
    address: 'Eskilstuna',
    kommun: 'Eskilstuna',
    lan: 'Södermanland',
    website: 'https://www.eskilstunaolkultur.se',
    products: ['öl'],
    onSiteSales: true,
    tastingRoom: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Stallarholmens Brygghus',
    description: 'Lokalt bryggeri vid Mälarens strand i Stallarholmen, Strängnäs.',
    address: 'Stallarholmen, Strängnäs',
    kommun: 'Strängnäs',
    lan: 'Södermanland',
    website: '',
    products: ['öl'],
    onSiteSales: true,
    tastingRoom: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Blacksta Brygghus',
    description: 'Hantverksbryggeriet i Nyköping med småskalig ölproduktion.',
    address: 'Blacksta, Nyköping',
    kommun: 'Nyköping',
    lan: 'Södermanland',
    website: '',
    products: ['öl'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Jürss Mejeri',
    description: 'Familjedrivet mejeri i Södermanland med gårdsost och mejeriprodukter.',
    address: 'Södermanland',
    kommun: 'Nyköping',
    lan: 'Södermanland',
    website: 'https://www.jurss.se',
    products: ['mejeri'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Rekarnes Kött',
    description: 'Lokalt slakteri och charkuteritillverkare i Rekarne, Södermanland med direktförsäljning.',
    address: 'Rekarne, Eskilstuna',
    kommun: 'Eskilstuna',
    lan: 'Södermanland',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Libink Agrikultur',
    description: 'Ekologisk gård och naturbruk i Södermanland med direktförsäljning av kött och grönsaker.',
    address: 'Södermanland',
    kommun: 'Strängnäs',
    lan: 'Södermanland',
    website: '',
    products: ['kött', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Solby Gård',
    description: 'Ekologisk gård i Södermanland med grönsaker, bär och direktförsäljning.',
    address: 'Solby, Södermanland',
    kommun: 'Nyköping',
    lan: 'Södermanland',
    website: '',
    products: ['grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Kilfroslunda Gård',
    description: 'Lantbruk och gårdsbutik i Södermanland med kött och ägg.',
    address: 'Kilfroslunda, Södermanland',
    kommun: 'Nyköping',
    lan: 'Södermanland',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Klippinge Gård',
    description: 'Gård i Södermanland med direktförsäljning av lokalt producerat kött.',
    address: 'Klippinge, Södermanland',
    kommun: 'Nyköping',
    lan: 'Södermanland',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Högtorp Gård',
    description: 'Lantgård i Södermanland med gårdsbutik och lokalproducerade produkter.',
    address: 'Högtorp, Södermanland',
    kommun: 'Katrineholm',
    lan: 'Södermanland',
    website: '',
    products: ['kött', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Långbro Gård',
    description: 'Naturbruk i Södermanland med ekologisk produktion och direktförsäljning.',
    address: 'Långbro, Södermanland',
    kommun: 'Strängnäs',
    lan: 'Södermanland',
    website: '',
    products: ['kött', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Ojagård',
    description: 'Ekogård i Södermanland med direktförsäljning.',
    address: 'Oja, Södermanland',
    kommun: 'Nyköping',
    lan: 'Södermanland',
    website: '',
    products: ['kött', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Andebols Gård',
    description: 'Ekologisk gård i Södermanland med nöt och lamm, direktförsäljning.',
    address: 'Andebols, Södermanland',
    kommun: 'Katrineholm',
    lan: 'Södermanland',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Fogdö Mat och Keramik',
    description: 'Gård på Fogdö i Strängnäs med lokalproducerad mat och hantverk.',
    address: 'Fogdö, Strängnäs',
    kommun: 'Strängnäs',
    lan: 'Södermanland',
    website: '',
    products: ['kött', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Mörraro Odlingar',
    description: 'Odlingar och naturupplevelser vid Mörraro i Södermanland.',
    address: 'Mörraro, Södermanland',
    kommun: 'Nyköping',
    lan: 'Södermanland',
    website: '',
    products: ['grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Hornuddens Trädgård',
    description: 'Ekologisk trädgård i Södermanland med grönsaker och direktförsäljning.',
    address: 'Hornudden, Södermanland',
    kommun: 'Gnesta',
    lan: 'Södermanland',
    website: '',
    products: ['grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Millert Dahlén Kött & Vilt',
    description: 'Lokalt producerat kött och vilt från Södermanland, direktförsäljning.',
    address: 'Södermanland',
    kommun: 'Nyköping',
    lan: 'Södermanland',
    website: '',
    products: ['kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Lindeborgs Vingård',
    description: 'Vingård i Södermanland med svensk gårdsvin produktion.',
    address: 'Lindeborgs, Flen',
    kommun: 'Flen',
    lan: 'Södermanland',
    website: '',
    products: ['vin'],
    onSiteSales: true,
    tastingRoom: true,
    gardsförsäljningLicense: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Turinge Ost & Vin',
    description: 'Ostbutik och vinförsäljning i Turinge, Södertälje.',
    address: 'Turinge, Södertälje',
    kommun: 'Södertälje',
    lan: 'Södermanland',
    website: '',
    products: ['mejeri', 'vin'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Stavtorp',
    description: 'Gård och naturgård i Södermanland med direktförsäljning.',
    address: 'Stavtorp, Södermanland',
    kommun: 'Gnesta',
    lan: 'Södermanland',
    website: '',
    products: ['kött', 'grönsaker'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
  {
    name: 'Sigridslund',
    description: 'Gård i Södermanland med ekologisk odling.',
    address: 'Sigridslund, Södermanland',
    kommun: 'Strängnäs',
    lan: 'Södermanland',
    website: '',
    products: ['grönsaker', 'kött'],
    onSiteSales: true,
    isArchipelago: false,
    source: 'seed',
  },
];

function slugify(name) {
  return name.toLowerCase()
    .replace(/å/g, 'a').replace(/ä/g, 'a').replace(/ö/g, 'o')
    .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/, '');
}

// Add IDs and defaults
const processedFarms = farms.map((f, i) => ({
  id: slugify(f.name) || `farm-${i + 1}`,
  name: f.name,
  description: f.description || '',
  address: f.address || '',
  kommun: f.kommun || f.address.split(',')[0].trim() || '',
  lan: f.lan,
  lat: null,
  lng: null,
  website: f.website || '',
  phone: f.phone || '',
  email: f.email || '',
  products: f.products || ['annat'],
  onSiteSales: f.onSiteSales !== undefined ? f.onSiteSales : true,
  tastingRoom: f.tastingRoom || false,
  gardsförsäljningLicense: f.gardsförsäljningLicense || false,
  isArchipelago: f.isArchipelago || false,
  openingHours: f.openingHours || '',
  season: f.season || 'Kontakta för öppettider',
  source: f.source,
}));

function main() {
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, JSON.stringify(processedFarms, null, 2));

  const byCounty = {};
  processedFarms.forEach(f => { byCounty[f.lan] = (byCounty[f.lan] || 0) + 1; });

  console.log('[Seed Farms] Curated farms:');
  console.log(`  Total: ${processedFarms.length}`);
  Object.entries(byCounty).forEach(([k, v]) => console.log(`  ${k}: ${v}`));

  return processedFarms;
}

module.exports = { main };
if (require.main === module) main();
